"""add_encrypted_body_to_processed_email

Revision ID: d8b67e3d3551
Revises: a00b127276e3
Create Date: 2025-12-18 15:13:07.389503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel
# revision identifiers, used by Alembic.
revision: str = 'd8b67e3d3551'
down_revision: Union[str, None] = 'a00b127276e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manualrule', sa.Column('confidence', sa.Float(), nullable=False, server_default='1.0'))
    op.add_column('manualrule', sa.Column('is_shadow_mode', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('manualrule', sa.Column('match_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('processedemail', sa.Column('encrypted_body', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('processedemail', sa.Column('encrypted_html', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('processedemail', sa.Column('retention_expires_at', sa.DateTime(), nullable=True))
    op.alter_column('processedemail', 'email_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('processedemail', 'subject',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('processedemail', 'sender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('processedemail', 'received_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('processedemail', 'processed_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('processedemail', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('processedemail', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('processedemail', 'processed_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('processedemail', 'received_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('processedemail', 'sender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('processedemail', 'subject',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('processedemail', 'email_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('processedemail', 'retention_expires_at')
    op.drop_column('processedemail', 'encrypted_html')
    op.drop_column('processedemail', 'encrypted_body')
    op.drop_column('manualrule', 'match_count')
    op.drop_column('manualrule', 'is_shadow_mode')
    op.drop_column('manualrule', 'confidence')
    # ### end Alembic commands ###
