// lib/config.js - Enhanced to catch all types of bills and receipts
export const CONFIG = {
  // Receipt detection patterns - now includes utility bills, subscriptions, etc.
  RECEIPT_KEYWORDS: [
    // Original receipt keywords
    "receipt",
    "invoice",
    "order confirmation",
    "payment confirmation",
    "purchase confirmation",
    "transaction",
    "billing",
    "statement",
    "order summary",
    "thank you for your order",
    "payment received",
    "order complete",
    "delivery confirmation",
    "order placed",

    // Utility & Service Bills
    "bill",
    "bill total",
    "payment due",
    "autopay",
    "auto pay",
    "account statement",
    "monthly statement",
    "service charge",
    "electricity bill",
    "electric bill",
    "gas bill",
    "water bill",
    "internet bill",
    "phone bill",
    "cable bill",
    "wifi bill",
    "utility bill",
    "service bill",
    "account balance",

    // Subscription & Recurring Services
    "subscription",
    "membership",
    "renewal",
    "auto-renewal",
    "recurring payment",
    "monthly charge",
    "annual fee",
    "subscription renewal",
    "plan renewal",
    "service renewal",

    // Banking & Financial
    "bank statement",
    "credit card statement",
    "payment processed",
    "charge posted",
    "direct debit",
    "automatic payment",
    "payment confirmation",
    "transfer confirmation",

    // Insurance & Healthcare
    "insurance premium",
    "policy payment",
    "copay",
    "co-pay",
    "medical bill",
    "dental bill",
    "prescription",
    "pharmacy",
    "insurance bill",
    "premium due",
    "deductible",

    // Common Receipt Phrases
    "total amount",
    "amount due",
    "balance due",
    "past due",
    "payment reminder",
    "final notice",
    "overdue",
    "paid in full",
    "payment thank you",
    "payment received",

    // Online Services
    "digital receipt",
    "e-receipt",
    "electronic receipt",
    "purchase summary",
    "order details",
    "shipping confirmation",
    "delivery receipt",
    "pickup confirmation",
  ],

  // Known receipt senders - greatly expanded
  RECEIPT_SENDERS: [
    // E-commerce & Retail
    "amazon",
    "walmart",
    "target",
    "costco",
    "bestbuy",
    "best buy",
    "homedepot",
    "home depot",
    "lowes",
    "lowe's",
    "macys",
    "macy's",
    "nordstrom",
    "kohls",
    "kohl's",
    "jcpenney",
    "sears",
    "ebay",
    "etsy",
    "wayfair",
    "overstock",
    "alibaba",
    "shopify",

    // Food & Restaurants
    "starbucks",
    "mcdonalds",
    "subway",
    "chipotle",
    "panera",
    "dominos",
    "pizza hut",
    "papa johns",
    "taco bell",
    "kfc",
    "burger king",
    "wendys",
    "wendy's",
    "chick-fil-a",
    "dunkin",

    // Food Delivery & Rideshare
    "uber",
    "lyft",
    "doordash",
    "grubhub",
    "ubereats",
    "postmates",
    "instacart",
    "shipt",
    "gopuff",
    "seamless",
    "caviar",

    // Utilities & Telecom
    "att",
    "at&t",
    "verizon",
    "tmobile",
    "t-mobile",
    "sprint",
    "comcast",
    "xfinity",
    "spectrum",
    "cox",
    "optimum",
    "fios",
    "directv",
    "dish",
    "centurylink",
    "frontier",

    // Streaming & Digital Services
    "netflix",
    "hulu",
    "disney",
    "hbo",
    "amazon prime",
    "apple",
    "spotify",
    "pandora",
    "youtube",
    "twitch",
    "zoom",
    "slack",
    "microsoft",
    "office365",
    "google",
    "dropbox",
    "icloud",

    // Payment Services
    "paypal",
    "venmo",
    "cashapp",
    "zelle",
    "square",
    "stripe",
    "chase",
    "bank of america",
    "wells fargo",
    "citi",
    "capital one",
    "american express",
    "discover",
    "mastercard",
    "visa",

    // Software & SaaS
    "adobe",
    "microsoft",
    "google",
    "salesforce",
    "hubspot",
    "mailchimp",
    "constant contact",
    "quickbooks",
    "turbotax",
    "norton",
    "mcafee",
    "avg",
    "bitdefender",

    // Travel & Transportation
    "airbnb",
    "booking.com",
    "expedia",
    "hotels.com",
    "marriott",
    "hilton",
    "hyatt",
    "delta",
    "american airlines",
    "united",
    "southwest",
    "jetblue",
    "alaska airlines",
    "spirit",
    "enterprise",
    "hertz",
    "avis",
    "budget",
    "national",

    // Healthcare & Insurance
    "blue cross",
    "aetna",
    "cigna",
    "humana",
    "kaiser",
    "anthem",
    "cvs",
    "walgreens",
    "rite aid",
    "pharmacy",
    "urgent care",

    // Home Services
    "pest control",
    "lawn care",
    "cleaning service",
    "handyman",
    "plumber",
    "electrician",
    "hvac",
    "security system",

    // Fitness & Wellness
    "planet fitness",
    "la fitness",
    "24 hour fitness",
    "ymca",
    "orange theory",
    "soulcycle",
    "peloton",
    "fitbit",

    // Auto & Gas
    "shell",
    "exxon",
    "bp",
    "chevron",
    "mobil",
    "texaco",
    "speedway",
    "wawa",
    "circle k",
    "valero",
    "sunoco",
    "jiffy lube",
    "valvoline",
    "midas",
    "autozone",
    "pepboys",

    // Government & Official
    "irs",
    "dmv",
    "city of",
    "county of",
    "state of",
    "toll",
    "parking",
    "traffic",
    "court",
    "license",
    "registration",
  ],

  // Email templates
  FORWARD_TEMPLATE: {
    subject: "📧 Receipt Forward: {originalSubject}",
    footer: `
    
---
Receipt Auto-Forwarder
Reply with commands to manage your preferences:
• "STOP {sender}" - Block this sender
• "STOP {category}" - Block category (e.g. "STOP utilities")
• "MORE {sender}" - Always forward from this sender
• "SETTINGS" - View all your preferences
    `,
  },
};
